Commit 01.05.2023
alexxk2/LayoutMake pull request #7
Opened 2023-05-01 19:51 UTC by alexxk2

-1 коммит по 14 спринту

2023-05-03 15:42 UTC, NoDopezzz requested changes

2023-05-03 15:42 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/PlayerActivity.kt
> +    private lateinit var timerText: Runnable
⏫ Лучше стараться задавать имена переменных, которые отсылают на их тип. Например имя  `timerText` наталкивается на то, что это `String` или `TextView` переменная.

2023-05-03 15:42 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/PlayerActivity.kt
> +        timerText = object : Runnable{
⏫ Нет необходимости делать `timeText` `lateinit` и задавать в `onCreate`. Мы можем сделать это сразу при инициализации класса

2023-05-03 15:42 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/PlayerActivity.kt
> +    }
⏫ В названии константных переменных, лучше указывать название величины. В данном случае `TIMER_UPDATE_INTERVAL_MS`

2023-05-03 15:42 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/adapters/utils/TrackViewHolder.kt
> +    private var isClickAllowed = true
⚠️ Если мы сохраняем `isClickAllowed` для каждого отдельного элемента поиска, то у нас все равно остается возможность вызвать одновременное открытие карточки плеера, если одновременно нажать на два различных трека.
Лучше логику обработки нажатия вытащить в `Activity`, там же реализовать и click-debounce

2023-05-03 15:42 UTC, NoDopezzz commented on app/src/main/res/drawable/ic_pause_day.xml
> +      android:fillColor="#1A1B22"/>
⏫ Цвета в векторных изображениях также можно выносить в файл ресурсов. Так, можно организовать более гибкую дизайн-систему приложения.
Кроме того, это поможет экономить занимаемое ресурсами место, если нам нужно иметь иконки разных цветов для разных тем приложения. Ведь вместо того, чтобы создавать две иконки и класть в `drawable` и `drawable-night`, мы можем создать одну иконку в drawable, а файл ресурса с цветом будет задан в `values` и `values-night`

2023-05-03 15:42 UTC, NoDopezzz commented on app/src/main/res/layout/activity_player.xml
> +        <ImageButton
⏫ Альтернативным и более эффективным с точки зрения рендеринга решением было бы использовать один `ImageButton` и просто менять его рисунок через `setImageDrawable`:

- `setImageDrawable` вызывает перерисовку текущей `View` - метод `invalidate`
- метод `setVisibility` (_с `VISIBLE` на `INVISIBLE` или наоборот_) также вызывает метод `invalidate`. Но в таком решении нам нужно изменить видимость двух кнопок, поэтому `invalidate` вызывается дважды

Вообще мелочь для таких маленьких кнопок, но приятно)

2023-05-04 12:59 UTC, alexxk2 commented on app/src/main/res/layout/activity_player.xml
> +        <ImageButton
Осознанно решил делать 2 кнопки, т.к. для них можно написать ночные стили, а как ты предложил выше(с ночными и дневными цветами) я никогда не делал, но буду иметь ввиду

2023-05-04 16:52 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/adapters/TrackAdapter.kt
> +    class TrackViewHolder(val binding: TrackItemBinding): RecyclerView.ViewHolder(binding.root)
⏫ Совсем опустошать `ViewHolder` конечно не надо было) Не стоит нагружать адаптер логикой отрисовки. Весь биндинг можно было оставить внутри `TrackViewHolder` и просто передавать туда слушатель для клика

2023-05-04 20:21 UTC, merged