15 sprint Pull
alexxk2/LayoutMake pull request #8
Opened 2023-05-25 06:56 UTC by alexxk2

-1 коммит по 15 спринту

2023-05-26 10:48 UTC, NoDopezzz requested changes

2023-05-26 10:48 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/data/player/Player.kt
> +interface Player {
⏫ Интерфейс плеера нами будет использоваться в domain слое, а реализация лежать в data.
Важно помнить, что интерфейсы должны находиться именно в тех слоях, которые их используют для обеспечения правильной инверсии зависимостей

2023-05-26 10:48 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/data/player/Player.kt
> +    fun getPlayerState():LiveData<Int>
⚠️ [Лучше избегать](https://proandroiddev.com/no-more-livedata-in-your-repository-there-are-better-options-25a7557b0730) использования `LiveData` в слоях, не относящихся к `presentation`. Дело в том, что `LiveData` обладает логикой касательно жизненого цикла `Fragment'а` или `Activity`, которые на нее подписаны, а эта логика тесно завязана на Android компонентах. [Google сами не рекомендуют](https://developer.android.com/topic/libraries/architecture/livedata#livedata-in-architecture) использовать `LiveData` для стейт менеджмента в репозиторях.

Если есть желание добавить щепотку реактивности в наш код, но при этом не нарушать CLEAN можно сделать следующее:
- Использоваться `RxJava` (_устаревший подход_)
- Использовать `Coroutine Flow`
- Передавать кастомный слушатель и вручную его удалять при `onDestroy` в `Presenter'`е.

Первые два варианта предполагают добавление новых библиотек и изучение тем, которые нами в данном курсе не рассматриваются. Но второй вариант вполне прост в реализации и не требует сложных доработок.

2023-05-26 10:48 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/domain/usecases/GetPlayerStateUseCase.kt
> +    fun execute():LiveData<Int> = playerRepository.getPlayerState()
⏫ Одним из вариантов реализации UseCase является переопределение стандартного оператора `invoke`:
```
operator fun invoke(): LiveData<Int> = playerRepository.getPlayerState()
```

- В этом случае мы говорим однозначно, что UseCase обладает только одним методом
- Теперь мы можем вызывать UseCase' следующим образом:
```
val getPlayerStateUseCase = GetPlayerStateUseCase(playerRepository)
getPlayerStateUseCase() // Возвращается LiveData
```

2023-05-26 10:48 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/presentation/presenters/player/PlayerPresenter.kt
> +    private val playerRepositoryImpl = PlayerRepositoryImpl(mediaPlayerImpl)
⚠️ Реализацию `PlayerRepository` стоит также передавать через `Creator` - аналогично тому, как ты сделал `Presenter`. Вообще в идеале Presenter ничего не должен знать про `PlayerRepositoryImpl` и оперировать только интерфейсом `PlayerRepository`

2023-05-26 16:21 UTC, alexxk2 commented on app/src/main/java/com/example/layoutmake/data/player/Player.kt
> +interface Player {
@NoDopezzz Он же используется в data слое, а домэйн использует интерфейс PlayerRepository

2023-05-27 10:11 UTC, NoDopezzz commented on app/src/main/java/com/example/layoutmake/data/player/Player.kt
> +interface Player {
Domain слой будет обращаться к интерфейсу `PlayerRepository` при этом ничего не зная про `PlayerRepoistoryImpl`, поэтому `PlayerRepository` также должен лежать в domain. На подобие других репозиториев, которые используются у тебя в проекте.

2023-05-27 10:13 UTC, NoDopezzz approved these changes

2023-06-07 07:13 UTC, merged